spring:
  application:
    name: kakao-oauth-practice

kakao:
  client-id: "a8a7a567b7c1dea7e52449ab28b8a1c7"
  redirect-uri : "http://localhost:8080/login/oauth2/code/kakao"
  auth-uri: "https://kauth.kakao.com/oauth/authorize"
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"
